import type { NextPage } from 'next'
import '../types/app.d.ts'
import Head from 'next/head'
import Searcher from '../components/organisms/Searcher'
// import styles from '../styles/Home.module.scss'
import theme from "../theme"
import globals from "../globals"
import styled, { StyledComponent } from "styled-components"
import settings from '../public/settings.json'
import { AdSenseAds } from '../components/atoms/AdsenseAds'

const AppContainer = styled.div`
  padding: 0;
  max-width: ${globals.pageMaxWidth}px;
  margin: 0 auto;
`;
const AppMain = styled.main`
  padding: 4rem 0 0 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
const AppTitle = styled.div`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;
`;
const Author = styled.div`
  width: 100%;
`;
const AuthorSiteLink = styled.a`
  color: #0070f3;
  text-decoration: none;

  &:hover,
  &:focus,
  &:active {
    text-decoration: underline;
  }
`;
const AuthorInner = styled.div`
  margin-right: 18px;
  display: flex;
  flex-direction: row;
  flex-wrap: nowrap;
  justify-content: flex-end;
  align-items: center;
`;
const AppDescription = styled.p`
  text-align: center;
  margin: 2rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
`;
const PoweredBy = styled.div`
  margin-right: 8px;
`;

const Home: NextPage = () => {

  const appSettings: AppSettings = settings;

  return (
    <AppContainer>
      <Head>
        <title>レンタルマンガ横断検索</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <AppMain>
        <AdSenseAds></AdSenseAds>
        <AppTitle>
          レンタルマンガ横断検索
        </AppTitle>
        <Author>
          <AuthorSiteLink href="https://slash-mochi.net" target="_blank" rel="noopener noreferrer">
            <AuthorInner>
              <PoweredBy>Powered by Mochi</PoweredBy>
              <img src="slash-mochi.png" alt="Slash Mochi Logo" height={32} width={32} />
            </AuthorInner>
          </AuthorSiteLink>
        </Author>
        <AppDescription>
          複数のマンガレンタルサイトを一括で横断検索します。
        </AppDescription>
      </AppMain>
      <Searcher siteSettings={appSettings.sites}></Searcher>
    </AppContainer>
  )
}

export default Home;