import type { NextPage } from 'next'
import '../types/app.d.ts'
import Head from 'next/head'
import Searcher from '../components/organisms/Searcher'
import styles from '../styles/Home.module.scss'
import settings from '../public/settings.json'

const Home: NextPage = () => {

  const appSettings: AppSettings = settings;

  return (
    <div className={styles.container}>
      <Head>
        <title>レンタルマンガ横断検索</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          レンタルマンガ横断検索
        </h1>
        <div className={styles.author}>
          <a href="https://slash-mochi.net" target="_blank" rel="noopener noreferrer">
            <div className={styles.authorInner}>
              <div className={styles.poweredBy}>Powered by Mochi</div>
              <img src="/slash-mochi.png" alt="Slash Mochi Logo" height={32} width={32} />
            </div>
          </a>
        </div>
        <p className={styles.description}>
          複数のマンガレンタルサイトを一括で横断検索します。
        </p>
      </main>
      <Searcher siteSettings={appSettings.sites}></Searcher>
    </div>
  )
}

export default Home
